import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern-compiler',
        silenceDeprecations: [
          'import',
          'global-builtin',
          'color-functions',
          'mixed-decls',
          'legacy-js-api'
        ]
      }
    }
  },
  test: {
    environment: 'jsdom',
    globals: true,
    // The suite must not depend on the environment it runs in. .env.local is
    // generated by a deploy and gitignored, so without these the tests pass on
    // a machine that has deployed and fail everywhere else - CI included.
    env: {
      VITE_API_BASE: 'https://api.test.invalid',
      VITE_COGNITO_DOMAIN: 'test.auth.eu-north-1.amazoncognito.com',
      VITE_USER_POOL_ID: 'eu-north-1_test',
      VITE_USER_POOL_CLIENT_ID: 'test-client-id',
      VITE_AWS_REGION: 'eu-north-1',
      VITE_BRAND_SHORT: 'Acme',
      VITE_BRAND_TAGLINE: 'Inbox',
      VITE_BRAND_FULL: 'Acme Ltd'
    },
    setupFiles: ['./test/setup.js'],
    include: ['test/unit/**/*.test.js'],
    exclude: ['node_modules/**']
  }
})
