// Build-time configuration for the inbox web app.
//
// The original kept a hostname -> environment map with the API URL and
// Cognito ids for each environment written into this file. That cannot ship to
// a second company: the ids are per-account, so a new deployment would mean
// editing source. Everything now comes from Vite env vars, which
// `scripts/deploy.mjs` writes into .env.local from the deployment profile and
// the CloudFormation outputs, so the same source builds for any deployment.
//
// For local work, copy the values from a deployed stack into .env.local, or
// point VITE_API_BASE at the local dev server (npm run dev in services/inbox,
// port 3600).

const ENV_VARS = (typeof import.meta !== 'undefined' && import.meta.env) || {}

const required = (key) => {
  const value = ENV_VARS[key]
  if (!value) {
    // Fail loudly at boot rather than rendering a login page that silently
    // cannot authenticate: a missing pool id is otherwise a blank redirect.
    console.error(
      `[config] ${key} is not set. Build with .env.local generated by ` +
        `scripts/deploy.mjs, or copy one from a deployed stack.`
    )
  }
  return value || ''
}

export const CONFIG = {
  apiBase: required('VITE_API_BASE'),
  cognito: {
    domain: required('VITE_COGNITO_DOMAIN'),
    userPoolId: required('VITE_USER_POOL_ID'),
    clientId: required('VITE_USER_POOL_CLIENT_ID'),
    region: ENV_VARS.VITE_AWS_REGION || 'eu-north-1'
  }
}

// Org membership comes from the signed JWT claim, so one deployed web app can
// serve every tenant in its account. Nothing here is per-tenant.
export const BRAND = {
  short: ENV_VARS.VITE_BRAND_SHORT || 'Inbox',
  tagline: ENV_VARS.VITE_BRAND_TAGLINE || 'Inbox',
  full: ENV_VARS.VITE_BRAND_FULL || 'Inbox',
  // Static paths under /brand, staged from the deployment profile at build
  // time. Empty means this deployment configured no artwork, and the app uses
  // its own neutral mark - no company's logo is committed to product code.
  logo: ENV_VARS.VITE_BRAND_LOGO || '',
  logoDark: ENV_VARS.VITE_BRAND_LOGO_DARK || ENV_VARS.VITE_BRAND_LOGO || ''
}

// Kept for callers that still branch on it; the deployed environment name is
// now build-time config rather than something guessed from the hostname.
export const ENV = ENV_VARS.VITE_ENVIRONMENT || 'dev'

export default CONFIG
